In [97]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
from sklearn.pipeline import Pipeline

In [98]:
df=pd.read_csv('Thyroid.csv')

In [99]:
df.head()

,Age,Gender,Smoking,Hx Smoking,Hx Radiothreapy,Thyroid Function,Physical Examination,Adenopathy,Pathology,Focality,Risk,T,N,M,Stage,Response,Recurred
0,27,F,No,No,No,Euthyroid,Single nodular goiter-left,No,Micropapillary,Uni-Focal,Low,T1a,N0,M0,I,Indeterminate,No
1,34,F,No,Yes,No,Euthyroid,Multinodular goiter,No,Micropapillary,Uni-Focal,Low,T1a,N0,M0,I,Excellent,No
2,30,F,No,No,No,Euthyroid,Single nodular goiter-right,No,Micropapillary,Uni-Focal,Low,T1a,N0,M0,I,Excellent,No
3,62,F,No,No,No,Euthyroid,Single nodular goiter-right,No,Micropapillary,Uni-Focal,Low,T1a,N0,M0,I,Excellent,No
4,62,F,No,No,No,Euthyroid,Multinodular goiter,No,Micropapillary,Multi-Focal,Low,T1a,N0,M0,I,Excellent,No

In [100]:
df['Adenopathy'].unique()

array(['No', 'Right', 'Extensive', 'Left', 'Bilateral', 'Posterior'],
      dtype=object)

In [101]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 383 entries, 0 to 382
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Age                   383 non-null    int64
 1   Gender                383 non-null    object
 2   Smoking               383 non-null    object
 3   Hx Smoking            383 non-null    object
 4   Hx Radiothreapy       383 non-null    object
 5   Thyroid Function      383 non-null    object
 6   Physical Examination  383 non-null    object
 7   Adenopathy            383 non-null    object
 8   Pathology             383 non-null    object
 9   Focality              383 non-null    object
 10  Risk                  383 non-null    object
 11  T                     383 non-null    object
 12  N                     383 non-null    object
 13  M                     383 non-null    object
 14  Stage                 383 non-null    object
 15  Response              383 non-null    object
 16  Recurred              383 non-null    object
dtypes: int64(1), object(16)
memory usage: 51.0+ KB

In [102]:
df.describe()

              Age
count  383.000000
mean    40.866841
std     15.134494
min     15.000000
25%     29.000000
50%     37.000000
75%     51.000000
max     82.000000

In [103]:
df['Gender']=df['Gender'].replace({'F':0,'M':1})
df['Smoking']=df['Smoking'].replace({'No':0,'Yes':1})
df['Hx Smoking']=df['Hx Smoking'].replace({'No':0,'Yes':1})
df['Hx Radiothreapy']=df['Hx Radiothreapy'].replace({'No':0,'Yes':1})
df['Recurred']=df['Recurred'].replace({'No':0,'Yes':1})

C:\Users\user\AppData\Local\Temp\ipykernel_28308\3550742576.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Gender']=df['Gender'].replace({'F':0,'M':1})
C:\Users\user\AppData\Local\Temp\ipykernel_28308\3550742576.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Smoking']=df['Smoking'].replace({'No':0,'Yes':1})
C:\Users\user\AppData\Local\Temp\ipykernel_28308\3550742576.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Hx Smoking']=df['Hx Smoking'].replace({'No':0,'Yes':1})
C:\Users\user\AppData\Local\Temp\ipykernel_28308\3550742576.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Hx Radiothreapy']=df['Hx Radiothreapy'].replace({'No':0,'Yes':1})
C:\Users\user\AppData\Local\Temp\ipykernel_28308\3550742576.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Recurred']=df['Recurred'].replace({'No':0,'Yes':1})

In [104]:
df.head(5)

,Age,Gender,Smoking,Hx Smoking,Hx Radiothreapy,Thyroid Function,Physical Examination,Adenopathy,Pathology,Focality,Risk,T,N,M,Stage,Response,Recurred
0,27,0,0,0,0,Euthyroid,Single nodular goiter-left,No,Micropapillary,Uni-Focal,Low,T1a,N0,M0,I,Indeterminate,0
1,34,0,0,1,0,Euthyroid,Multinodular goiter,No,Micropapillary,Uni-Focal,Low,T1a,N0,M0,I,Excellent,0
2,30,0,0,0,0,Euthyroid,Single nodular goiter-right,No,Micropapillary,Uni-Focal,Low,T1a,N0,M0,I,Excellent,0
3,62,0,0,0,0,Euthyroid,Single nodular goiter-right,No,Micropapillary,Uni-Focal,Low,T1a,N0,M0,I,Excellent,0
4,62,0,0,0,0,Euthyroid,Multinodular goiter,No,Micropapillary,Multi-Focal,Low,T1a,N0,M0,I,Excellent,0

In [105]:
column=['Thyroid Function', 'Physical Examination','Pathology',
       'Focality', 'Risk', 'T', 'N', 'M','Adenopathy', 'Stage', 'Response']

In [115]:
df.drop(columns=['Thyroid Function', 'Physical Examination','Pathology',
       'Focality', 'Risk', 'T', 'N', 'M','Adenopathy', 'Stage', 'Response'],axis=1,inplace=True)

In [116]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder

In [117]:
df.head()

   Age  Gender  Smoking  Hx Smoking  Hx Radiothreapy  Recurred
0   27       0        0           0                0         0
1   34       0        0           1                0         0
2   30       0        0           0                0         0
3   62       0        0           0                0         0
4   62       0        0           0                0         0

In [118]:
df['Recurred'].value_counts()

Recurred
0    275
1    108
Name: count, dtype: int64

In [125]:
Q1=df['Recurred'].quantile(0.25)
Q3=df['Recurred'].quantile(0.75)
IQR=Q3-Q1
lower=Q1-1.5*IQR
upper=Q3+1.5*IQR
df[(df['Recurred']<lower)|(df['Recurred']>upper)]

Empty DataFrame
Columns: [Age, Gender, Smoking, Hx Smoking, Hx Radiothreapy, Recurred]
Index: []

In [128]:
from sklearn import SMOTE

ImportError: cannot import name 'SMOTE' from 'sklearn.utils' (C:\Users\user\anaconda3\envs\pfa\Lib\site-packages\sklearn\utils\__init__.py)